name: paginate_firestore
description: A flutter package to simplify pagination with firestore data.
version: 0.3.1
homepage: https://github.com/excogitatr/paginate_firestore
issue_tracker: https://github.com/excogitatr/paginate_firestore/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  cloud_firestore: ^4.14.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.2
